/**
 * Makes the recorded clips: one mp3 per distinct spoken text of every course, into audio/<code>/.
 *   npx tsx scripts/make-audio.ts [code]          make the missing clips
 *   npx tsx scripts/make-audio.ts --check [code]  list words without a clip, exit 1 if any
 * Needs espeak-ng (with the MBROLA voices for the better German one) and ffmpeg on the PATH. Existing clips are kept,
 * so only new words are made; delete audio/<code>/ to remake a course.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { COURSES } from '../hooks/courses'
import { LEVELS } from '../hooks/course'
import { clipAsset, spoken } from '../hooks/audio'
import { plain } from '../hooks/engine'

/** espeak-ng voice per course code: the MBROLA voices sound much better than the plain ones. */
const VOICE: Record<string, string> = { de: 'mb-de7', fr: 'mb-fr4' }
const FALLBACK: Record<string, string> = { de: 'de', fr: 'fr' }
const SPEED = '135' // words per minute: a little slower than natural, for learners

const args = process.argv.slice(2)
const checkOnly = args.includes('--check')
const only = args.find(a => !a.startsWith('--'))
let missing = 0
let made = 0
let kept = 0
for (const course of Object.values(COURSES)) {
  if (only && course.code !== only) continue
  const texts = new Map<string, string>() // spoken -> text to say
  for (const lv of LEVELS)
    for (const u of course.levels[lv])
      for (const l of u.lessons) {
        for (const [t] of l.words) texts.set(spoken(t), plain(t))
        for (const [t] of l.sentences) texts.set(spoken(t), plain(t))
      }
  if (!checkOnly) mkdirSync(`audio/${course.code}`, { recursive: true })
  const wanted = new Set<string>()
  for (const text of texts.values()) {
    const file = clipAsset(course.code, text)
    wanted.add(file.split('/').pop() as string)
    if (existsSync(file)) {
      kept++
      continue
    }
    if (checkOnly) {
      missing++
      console.log(`missing: ${course.code}: ${text}`)
      continue
    }
    let voice = VOICE[course.code] ?? course.code
    let wav = spawnSync('espeak-ng', ['-v', voice, '-s', SPEED, '--stdout', text], { maxBuffer: 1 << 26 })
    if (wav.status !== 0 || wav.stdout.length < 100) {
      voice = FALLBACK[course.code] ?? course.code
      wav = spawnSync('espeak-ng', ['-v', voice, '-s', SPEED, '--stdout', text], { maxBuffer: 1 << 26 })
    }
    if (wav.status !== 0) throw new Error(`espeak-ng failed for ${course.code}: ${text}`)
    const mp3 = spawnSync('ffmpeg', ['-v', 'error', '-y', '-i', 'pipe:0', '-ac', '1', '-ar', '22050', '-b:a', '32k', file], { input: wav.stdout })
    if (mp3.status !== 0) throw new Error(`ffmpeg failed for ${text}: ${mp3.stderr}`)
    made++
  }
  if (checkOnly) continue
  // Clips of words that left the course are removed.
  for (const f of readdirSync(`audio/${course.code}`)) if (f.endsWith('.mp3') && !wanted.has(f)) rmSync(`audio/${course.code}/${f}`)
  writeFileSync(`audio/${course.code}/README.txt`, `Generated by scripts/make-audio.ts with espeak-ng (${VOICE[course.code] ?? course.code}) and ffmpeg. ${wanted.size} clips.\n`)
  console.log(`${course.code}: ${wanted.size} clips`)
}
if (checkOnly) {
  console.log(missing ? `${missing} clips missing` : 'every word has a clip')
  process.exit(missing ? 1 : 0)
}
console.log(`made ${made}, kept ${kept}`)
